import type { PermissionKey } from '../auth/rbac';

export type ReportReadiness = 'available' | 'governed_calculation' | 'needs_setup';
export type ReportDefinition = {
  id: string;
  domain: string;
  title: string;
  description: string;
  readiness: ReportReadiness;
  permission: PermissionKey;
  bookId: string;
  sources: string[];
  dateBasis: string;
};

const domains: Record<string, { permission: PermissionKey; bookId: string; sources: string[]; dateBasis: string }> = {
  'Executive & financial': { permission: 'reports.executive', bookId: 'owner.pulse', sources: ['SalesInvoice', 'CreditNote', 'CustomerPayment', 'CustomerLedgerEntry', 'InventoryLotBalance', 'PurchaseOrderLine', 'DispatchChallan'], dateBasis: 'document effective date' },
  Sales: { permission: 'reports.sales', bookId: 'sales.product', sources: ['Lead', 'Activity', 'Quote', 'SalesOrder', 'SalesInvoice', 'SalesInvoiceLine'], dateBasis: 'createdAt / sentAt / issueDate by measure' },
  'Architect & customer': { permission: 'reports.sales', bookId: 'sales.product', sources: ['Customer', 'Architect', 'Quote', 'SalesOrder', 'SalesInvoice'], dateBasis: 'issueDate for value; cohort date for behavior' },
  'Quotes & orders': { permission: 'reports.sales', bookId: 'fulfilment.pipeline', sources: ['Quote', 'QuoteLine', 'SalesOrder', 'SalesOrderLine', 'DispatchChallan', 'SalesInvoice'], dateBasis: 'sentAt / createdAt / deliveredAt by stage' },
  'Product & pricing': { permission: 'reports.sales', bookId: 'sales.product', sources: ['Product', 'ProductAlias', 'TileSize', 'QuoteLine', 'SalesOrderLine', 'SalesInvoiceLine'], dateBasis: 'invoice issueDate for outcomes' },
  'Inventory & warehouse': { permission: 'reports.inventory', bookId: 'inventory.stock', sources: ['StockLocation', 'InventoryLot', 'InventoryLotBalance', 'InventoryLotLedgerEntry'], dateBasis: 'as-of generatedAt; receivedAt for aging' },
  'Procurement & vendor': { permission: 'reports.procurement', bookId: 'procurement.vendor', sources: ['Vendor', 'ProductVendor', 'ReorderPolicy', 'PurchaseDemand', 'PurchaseOrder', 'PurchaseOrderLine', 'GoodsReceiptNote', 'GoodsReceiptLine'], dateBasis: 'orderedAt / receivedDate by measure' },
  'Receivables & cash': { permission: 'reports.finance', bookId: 'finance.receivables', sources: ['SalesInvoice', 'CustomerPayment', 'CustomerAllocation', 'CreditNote', 'CustomerLedgerEntry', 'CustomerCreditProfile', 'CollectionTask'], dateBasis: 'as-of date / receivedAt by measure' },
  Fulfilment: { permission: 'reports.fulfilment', bookId: 'fulfilment.pipeline', sources: ['SalesOrderLine', 'Reservation', 'PickList', 'DispatchChallan', 'DispatchPackage', 'Shipment', 'DeliveryProof', 'ReturnOrder'], dateBasis: 'promisedDate / operational timestamp by measure' },
  'Documents & engagement': { permission: 'reports.audit', bookId: 'audit.quality', sources: ['QuoteShare', 'VaultAsset', 'VaultShare', 'DocumentJob', 'Notification'], dateBasis: 'createdAt / viewedAt / generatedAt by measure' },
  'Audit & quality': { permission: 'reports.audit', bookId: 'audit.quality', sources: ['AuditEvent', 'User', 'Session', 'SequenceCounter', 'AppSetting', 'Product', 'InventoryInwardBatch'], dateBasis: 'createdAt / updatedAt by entity' },
};

const rows: Array<[string, string, string, ReportReadiness]> = [
  ['Executive & financial','Management financial pulse','Invoices, collections, credits, AR and stock at cost','available'],['Executive & financial','Period-over-period bridge','Prior-period variance with comparable ranges','governed_calculation'],['Executive & financial','Order bookings to net sales','Bookings, unfulfilled, invoiced, credits and collections','governed_calculation'],['Executive & financial','Decision exception queue','Cross-domain overdue and approval items','governed_calculation'],['Executive & financial','Target versus actual','Versioned company targets compared with governed actuals','governed_calculation'],
  ['Sales','Sales by owner','Invoiced outcomes, orders and conversion','governed_calculation'],['Sales','Lead funnel cohort','Lead cohorts through quote/order/invoice','governed_calculation'],['Sales','Activity and stale leads','Follow-ups, last contact, next actions','available'],['Sales','Sales cycle time','Lead to quote/order elapsed days','governed_calculation'],['Sales','Performance ranking','Configurable rank by backed outcomes','governed_calculation'],
  ['Architect & customer','Architect portfolio','Quotes, conversion, invoiced sales and AR','governed_calculation'],['Architect & customer','Customer 360','Orders, invoices, payments, returns and credit','available'],['Architect & customer','Repeat and cohort retention','First invoice cohort and repeat behaviour','governed_calculation'],['Architect & customer','Customer revenue ranking','Net invoiced value and order frequency','governed_calculation'],['Architect & customer','Architect mapping exceptions','Legacy text versus architect master','governed_calculation'],
  ['Quotes & orders','Quote register analytics','Status, expiry, value, approval and versions','available'],['Quotes & orders','Quote-to-order conversion','Same-cohort document conversion','governed_calculation'],['Quotes & orders','Order fulfilment control tower','Allocation, backorder, dispatch and invoice','available'],['Quotes & orders','Uninvoiced dispatch','Eligible dispatch lines missing invoices','available'],['Quotes & orders','Superseded quote lineage','Version and replacement chain','available'],
  ['Product & pricing','Product/category sales','Invoice value and quantity by master dimensions','available'],['Product & pricing','Tile size/design performance','SKU facts joined to TileSize','available'],['Product & pricing','Discount realisation','Weighted discount by owner/category/customer','governed_calculation'],['Product & pricing','Realised gross margin','Invoice revenue less captured invoice-line cost with coverage','governed_calculation'],['Product & pricing','Historical quoted margin','Quoted value less captured product-cost snapshot with coverage','governed_calculation'],['Product & pricing','MRP verification coverage','Verified/source-backed MRP versus unverified SKU lines','available'],['Product & pricing','Alias and code coverage','Warehouse SKU, display code and searchable aliases','available'],['Product & pricing','Display sample register','Installed/removed samples by location and zone','available'],['Product & pricing','Catalogue media readiness','Primary/gallery image and description completeness','governed_calculation'],['Product & pricing','Master dimension integrity','Category, brand, finish, material, UOM and tax mappings','governed_calculation'],
  ['Inventory & warehouse','Stock by location and lot','All quantity buckets and lot cost','available'],['Inventory & warehouse','Inventory aging','Lot received-age buckets at cost','available'],['Inventory & warehouse','Slow/non-moving stock','Ledger issue velocity and days since outflow','governed_calculation'],['Inventory & warehouse','Stock count variance','Quantity and value by count session','available'],['Inventory & warehouse','Inventory period close','Closed snapshots and variance','available'],['Inventory & warehouse','Stock turns','Needs period snapshots plus governed COGS coverage','governed_calculation'],['Inventory & warehouse','Reservation and allocation','Quote/order reservations by product, lot and location','available'],['Inventory & warehouse','Lot traceability','Receipt-to-reservation-to-pick-to-dispatch-to-return','available'],['Inventory & warehouse','Stock transfer control','Requested, dispatched, received and damaged quantities','available'],['Inventory & warehouse','Opening stock audit','Approved opening sessions and posted cost basis','available'],['Inventory & warehouse','Hold/damage/quality exceptions','Non-sellable buckets by reason, lot and location','available'],['Inventory & warehouse','Expiry and shelf-life','Expiry/manufacture alerts where dates are captured','available'],['Inventory & warehouse','Reorder exception list','Balance versus reorder point/policy and pack multiple','available'],['Inventory & warehouse','Label and scan audit','Created, printed, canceled, voided and scanned labels','available'],['Inventory & warehouse','Legacy stock reconciliation','Legacy balances/movements versus universal lot ledger','governed_calculation'],
  ['Procurement & vendor','Purchase demand pipeline','Demand, ordered and received quantities','available'],['Procurement & vendor','Open PO commitment','Remaining quantity at line unit cost','governed_calculation'],['Procurement & vendor','Vendor fulfilment scorecard','Fill, lead days and inward damage','governed_calculation'],['Procurement & vendor','PO expected-date exceptions','Overdue open purchase orders','available'],['Procurement & vendor','Preferred vendor coverage','ProductVendor and ReorderPolicy readiness','available'],['Procurement & vendor','Cost history by SKU/vendor','PO/GRN unit-cost trend and last cost','governed_calculation'],['Procurement & vendor','GRN control register','Accepted, damaged, lot and attachment trace','available'],['Procurement & vendor','Supplier payables aging','Needs supplier invoices/payments/allocations','needs_setup'],
  ['Receivables & cash','Customer AR aging','Open invoice amounts by due-date bucket','available'],['Receivables & cash','Collections and payment mix','Posted payments by account and mode','available'],['Receivables & cash','Unapplied credit','Payment/credit sources not allocated','available'],['Receivables & cash','Collection task performance','Open, overdue, completed and outcomes','available'],['Receivables & cash','Credit limit and exposure','Open AR plus unbilled exposure versus customer limit','governed_calculation'],['Receivables & cash','Allocation audit','Payment/credit allocation to invoice and reversal lineage','available'],['Receivables & cash','Legacy receipt reconciliation','PaymentReceipt versus authoritative CustomerPayment migration','governed_calculation'],['Receivables & cash','P&L / cash flow / balance sheet','Needs general ledger, expenses and account masters','needs_setup'],
  ['Fulfilment','On-time delivery','Promised date versus delivered date','governed_calculation'],['Fulfilment','Pick-pack-dispatch cycle','Operational timestamp medians and p90','governed_calculation'],['Fulfilment','Dispatch backlog','Open jobs, challans and quantity gaps','available'],['Fulfilment','Package and box register','Packages, box counts, photos and packing actor/time','available'],['Fulfilment','Shipment and POD coverage','Transport, vehicle, delivery status and proof capture','available'],['Fulfilment','Returns and disposition','Accepted/resell/damaged/supplier return','available'],['Fulfilment','Credit note and refund lineage','Return to credit issue/unapplied/refund mode','available'],
  ['Documents & engagement','Quote share engagement','Views, last view, expiry, revoke and download permission','available'],['Documents & engagement','Vault asset register','File type, size, checksum, category and status','available'],['Documents & engagement','Vault share register','Shares, expiry, revoke, views and downloads allowed','available'],['Documents & engagement','Document generation SLA','Pending/failed/generated, retries and elapsed time','governed_calculation'],['Documents & engagement','Notification delivery queue','Unread, target role/user, entity and age','available'],
  ['Audit & quality','Audit event register','Actor, action, entity, reason and time','available'],['Audit & quality','Document failure register','Failed/retried generated documents','available'],['Audit & quality','Master-data readiness','Current product completeness with direct correction paths','governed_calculation'],['Audit & quality','User and permission register','Active users, roles, overrides and access review','available'],['Audit & quality','Session and password posture','Active/expired sessions and password change age','available'],['Audit & quality','Sequence integrity','Document number gaps/duplicates by governed sequence','governed_calculation'],['Audit & quality','App setting change register','Configuration state with audit lineage','governed_calculation'],['Audit & quality','Import/inward batch register','Legacy inward batch attachment and line traceability','available'],
];

const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '.').replace(/^\.|\.$/g, '');

export const REPORT_CATALOG: ReportDefinition[] = rows.map(([domain, title, description, readiness]) => ({
  id: `${slug(domain)}.${slug(title)}`,
  domain,
  title,
  description,
  readiness,
  ...domains[domain],
  sources: title === 'Target versus actual'
    ? [...domains[domain].sources, 'ReportingTarget']
    : title === 'Historical quoted margin'
      ? ['Quote', 'QuoteLine', 'governed cost snapshot when captured']
      : title === 'Realised gross margin'
        ? ['SalesInvoice', 'SalesInvoiceLine', 'InventoryLot.unitCost snapshot']
        : domains[domain].sources,
}));

export const REPORTING_SETUP_GUIDANCE = {
  targets: { classification: 'governed_entry', title: 'Targets and budgets', owner: 'Owner or administrator', actionHref: '/dashboard/reports/setup#target-entry', actionLabel: 'Set company targets', helpHref: '/dashboard/help#reporting-readiness', message: 'Add versioned monthly targets here; revisions and voids retain audit history.' },
  quoted_margin: { classification: 'governed_calculation', title: 'Historical quoted margin', owner: 'Sales operations and inventory owner', actionHref: '/dashboard/reports/setup#cost-provenance', actionLabel: 'Review cost provenance', helpHref: '/dashboard/help#reporting-readiness', message: 'Quoted margin is shown only when a governed cost snapshot exists. Product defaults are never treated as cost; uncovered lines remain explicit.' },
  realised_margin: { classification: 'automatic_capture', title: 'Realised gross margin', owner: 'Inventory and finance operations', actionHref: '/dashboard/reports/setup#cost-provenance', actionLabel: 'Review cost provenance', helpHref: '/dashboard/help#reporting-readiness', message: 'Future invoice lines capture the dispatched lot cost automatically. Existing lines stay explicitly uncovered.' },
  master_data: { classification: 'existing_workflow', title: 'Master-data readiness', owner: 'Product master owner', actionHref: '/dashboard/products', actionLabel: 'Correct Product Master', helpHref: '/dashboard/help#reporting-readiness', message: 'Use existing Product, Tile, Size and alias masters; the report identifies exact exceptions.' },
  supplier_ap: { classification: 'external_or_module', title: 'Supplier payables', owner: 'Finance owner', actionHref: '/dashboard/reports/setup#supplier-ap', actionLabel: 'Review required source', helpHref: '/dashboard/help#reporting-readiness', message: 'Purchase orders and receipts are not supplier invoices or payments. Connect accounting or implement a dedicated AP subledger before reporting payables.' },
  accounting: { classification: 'external_integration', title: 'Accounting statements', owner: 'Finance owner', actionHref: '/dashboard/reports/setup#accounting', actionLabel: 'Review integration path', helpHref: '/dashboard/help#reporting-readiness', message: 'A governed chart of accounts, journal, expenses and opening balances must come from an accounting integration or dedicated ledger.' },
} as const;

export const REPORT_BOOKS = ['owner.pulse', 'sales.product', 'inventory.stock', 'procurement.vendor', 'finance.receivables', 'fulfilment.pipeline', 'audit.quality'] as const;

export function findReportDefinition(id: string): ReportDefinition | undefined {
  if ((REPORT_BOOKS as readonly string[]).includes(id)) {
    return REPORT_CATALOG.find((row) => row.bookId === id && row.readiness !== 'needs_setup');
  }
  return REPORT_CATALOG.find((row) => row.id === id);
}
