'use client';

import { gql, useMutation, useQuery } from '@apollo/client';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { useState } from 'react';
import { Activity, CalendarClock, FileSpreadsheet, ListChecks, MessageSquarePlus, Phone, UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { QueryErrorBanner } from '@/components/query-state';

const LEAD = gql`query LeadDetail($id: ID!) { lead(id: $id) { id title source stage expectedValue notes nextActionAt customer owner quotes followUps intents activities } }`;
const CREATE_INTENT = gql`mutation CreateLeadIntent($input: CreateLeadIntentInput!) { createLeadIntent(input: $input) }`;
const GENERATE = gql`mutation GenerateQuoteFromIntent($intentId: String!, $note: String) { generateQuoteFromIntent(intentId: $intentId, note: $note) }`;
function money(value: number) { return `₹${Math.round(Number(value || 0)).toLocaleString('en-IN')}`; }
function quoteTotal(lines:any){ return (Array.isArray(lines)?lines:[]).reduce((s,l)=>s+Number(l.qty||l.quantity||0)*Number(l.price||l.sellPrice||0),0); }

export default function LeadDetailPage(){
 const params=useParams(); const id=String(params.id); const [tab,setTab]=useState<'overview'|'intents'|'quotes'|'followups'|'activity'>('overview'); const [reason,setReason]=useState('Re-follow up'); const [notes,setNotes]=useState(''); const [rows,setRows]=useState('[{"category":"Sanitaryware","sku":"","name":"","qty":1,"unit":"PC","price":0}]');
 const {data,loading,error,refetch}=useQuery(LEAD,{variables:{id}}); const [createIntent,{loading:creatingIntent,error:createIntentError}]=useMutation(CREATE_INTENT,{onCompleted:()=>{setNotes('');refetch();}}); const [generate,{loading:generating,error:generateError}]=useMutation(GENERATE,{onCompleted:()=>refetch()}); const lead=data?.lead;
 const mutationError = createIntentError || generateError;
 if(loading && !lead) return <div role="status" aria-live="polite" className="p-10 text-sm font-bold text-[#8b6b4c]">Loading lead...</div>;
 if(error && !lead) return <div className="p-6"><QueryErrorBanner error={error} onRetry={() => refetch()} /></div>;
 if(!lead) return <div className="p-10 text-sm font-bold text-[#8b6b4c]">Lead not found.</div>;
 return <div className="space-y-6 pb-10">
 {error ? <QueryErrorBanner error={error} onRetry={() => refetch()} /> : null}
 {mutationError ? <QueryErrorBanner error={mutationError} /> : null}
 <section className="rounded-[2.25rem] bg-[#211b16] p-7 text-white shadow-2xl shadow-[#211b16]/15"><p className="text-[10px] font-black uppercase tracking-[0.28em] text-[#e8c39b]">Lead command file</p><h1 className="mt-3 text-5xl font-black tracking-[-0.055em]">{lead.title}</h1><div className="mt-5 flex flex-wrap gap-3 text-sm font-bold text-[#d9c4a9]"><span className="rounded-full bg-white/10 px-4 py-2">{lead.stage}</span><span className="rounded-full bg-white/10 px-4 py-2">{lead.customer?.name}</span><span className="rounded-full bg-white/10 px-4 py-2">Sales: {lead.owner?.name}</span><span className="rounded-full bg-white/10 px-4 py-2">{money(lead.expectedValue)}</span></div></section>
 <section className="mp-card flex flex-wrap gap-2 rounded-[2rem] p-3">{[['overview','Overview',UserRound],['intents','Intents',ListChecks],['quotes','Quotes',FileSpreadsheet],['followups','Follow-ups',CalendarClock],['activity','History',Activity]].map(([key,label,Icon]: any)=><button key={key} onClick={()=>setTab(key)} className={`flex items-center gap-2 rounded-2xl px-4 py-3 text-sm font-black ${tab===key?'bg-[#211b16] text-white':'bg-white/70 text-[#5f4b3b]'}`}><Icon className="h-4 w-4"/>{label}</button>)}</section>
 {tab==='overview'&&<section className="grid gap-5 xl:grid-cols-[0.7fr_1.3fr]"><div className="mp-card rounded-[2rem] p-5"><h2 className="text-2xl font-black text-[#211b16]">Customer</h2><p className="mt-4 font-black text-[#211b16]">{lead.customer?.name}</p><p className="mt-1 text-sm font-bold text-[#8b6b4c]"><Phone className="mr-2 inline h-4 w-4"/>{lead.customer?.mobile}</p><p className="mt-1 text-sm font-bold text-[#8b6b4c]">{lead.customer?.siteAddress || lead.customer?.city}</p></div><div className="mp-card rounded-[2rem] p-5"><h2 className="text-2xl font-black text-[#211b16]">Lead notes</h2><p className="mt-4 whitespace-pre-wrap text-sm font-bold leading-6 text-[#6e563f]">{lead.notes || 'No notes yet.'}</p></div></section>}
 {tab==='intents'&&<section className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><div className="space-y-4">{(lead.intents||[]).map((intent:any)=><article key={intent.id} className="mp-card rounded-[2rem] p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-[#8b6b4c]">{intent.status} · {intent.intentType}</p><h3 className="mt-1 text-xl font-black text-[#211b16]">{intent.rows?.length||0} requirement rows</h3><p className="mt-1 text-sm font-bold text-[#7d6b5c]">{intent.notes}</p></div>{intent.status==='pending_quote'?<Button disabled={generating} onClick={()=>generate({variables:{intentId:intent.id,note:'Generated from lead detail'}})}>Generate quote</Button>:intent.quoteId?<Button asChild variant="outline"><Link href={`/dashboard/quotes/${intent.quoteId}`}>Open quote</Link></Button>:null}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{(intent.rows||[]).map((row:any,idx:number)=><div key={idx} className="rounded-2xl bg-white/75 p-4"><p className="font-black text-[#211b16]">{row.name||row.tileCode||row.sku||'Item'}</p><p className="text-xs font-bold text-[#8b6b4c]">{row.category||row.type} · Qty {row.qty||row.quantity||0} {row.uom||row.unit||'PC'}</p></div>)}</div></article>)}</div><div className="mp-card rounded-[2rem] p-5"><h2 className="flex items-center gap-2 text-2xl font-black text-[#211b16]"><MessageSquarePlus className="h-6 w-6 text-[#b57942]"/>New follow-up intent</h2><label className="mt-4 block space-y-2"><span className="text-[10px] font-black uppercase tracking-wider text-[#8b6b4c]">Reason</span><Input value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="mt-3 block space-y-2"><span className="text-[10px] font-black uppercase tracking-wider text-[#8b6b4c]">Rows JSON</span><textarea value={rows} onChange={e=>setRows(e.target.value)} className="min-h-40 w-full rounded-2xl border border-[#7a5b3c]/15 bg-white px-3 py-2 text-xs font-bold"/></label><label className="mt-3 block space-y-2"><span className="text-[10px] font-black uppercase tracking-wider text-[#8b6b4c]">Notes</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} className="min-h-24 w-full rounded-2xl border border-[#7a5b3c]/15 bg-white px-3 py-2 text-sm font-bold"/></label><Button className="mt-4 w-full" disabled={creatingIntent} onClick={()=>createIntent({variables:{input:{leadId:id,rows,notes,followUpReason:reason}}})}>Create intent</Button></div></section>}
 {tab==='quotes'&&<section className="space-y-3">{(lead.quotes||[]).map((quote:any)=><Link key={quote.id} href={`/dashboard/quotes/${quote.id}`} className="mp-card block rounded-[2rem] p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xl font-black text-[#211b16]">{quote.quoteNumber}</p><p className="text-sm font-bold text-[#8b6b4c]">{quote.status} · {quote.approvalStatus}</p></div><p className="text-2xl font-black text-[#211b16]">{money(quoteTotal(quote.lines))}</p></div></Link>)}</section>}
 {tab==='followups'&&<section className="grid gap-3">{(lead.followUps||[]).map((task:any)=><article key={task.id} className="mp-card rounded-[2rem] p-5"><p className="font-black text-[#211b16]">{task.status} · {new Date(task.dueAt).toLocaleString()}</p><p className="mt-2 text-sm font-bold text-[#8b6b4c]">{task.notes}</p></article>)}</section>}
 {tab==='activity'&&<section className="grid gap-3">{(lead.activities||[]).map((act:any)=><article key={act.id} className="mp-card rounded-[2rem] p-5"><p className="font-black text-[#211b16]">{act.type}</p><p className="mt-2 text-sm font-bold text-[#8b6b4c]">{act.message}</p><p className="mt-1 text-xs font-bold text-[#a7907c]">{new Date(act.createdAt).toLocaleString()}</p></article>)}</section>}
 </div>;
}
