'use client';

import Link from 'next/link';
import { useState } from 'react';
import { gql, useQuery } from '@apollo/client';
import { Boxes, CheckCircle2, ChevronLeft, ChevronRight, Search, Truck } from 'lucide-react';
import { QueryErrorBanner } from '@/components/query-state';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useDebouncedValue } from '@/hooks/use-debounced-value';

const DATA=gql`query PendingInwardQueue($search:String,$status:String,$sort:String,$skip:Int){purchaseDemandPage(search:$search,status:$status,sort:$sort,skip:$skip,take:40)}`;

export default function PendingInwardPage(){
 const[search,setSearch]=useState('');const[status,setStatus]=useState('all');const[sort,setSort]=useState('priority');const[page,setPage]=useState(0);
 const{data,loading,error,refetch}=useQuery(DATA,{variables:{search:useDebouncedValue(search,250)||undefined,status,sort,skip:page*40},fetchPolicy:'cache-and-network'});
 const result=data?.purchaseDemandPage||{};const rows=result.items||[];
 return <div className="space-y-5 pb-10">{error?<QueryErrorBanner error={error} onRetry={()=>refetch()}/>:null}
  <header className="flex flex-col justify-between gap-5 border-b border-[var(--line)] pb-5 pt-2 xl:flex-row xl:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[var(--ink-4)]">Sales confirmed · supply pending</p><h1 className="mt-1 font-display text-3xl font-bold">Pending inward queue</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--ink-3)]">A server-paged shortage queue tied to the same purchase demand, PO, GRN, lot and reservation lifecycle used everywhere else.</p></div><div className="flex gap-3"><div><p className="text-2xl font-semibold">{Number(result.total||0).toLocaleString('en-IN')}</p><p className="text-xs text-[var(--ink-4)]">Matching rows</p></div><Button asChild><Link href="/dashboard/procurement?view=demand"><Boxes className="mr-2 h-4 w-4"/>Create PO</Link></Button></div></header>
  <section className="mp-panel overflow-hidden"><div className="flex flex-col gap-3 border-b border-[var(--line)] p-4 lg:flex-row"><label className="relative min-w-0 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-[var(--ink-4)]"/><Input className="pl-9" value={search} onChange={(e)=>{setSearch(e.target.value);setPage(0)}} placeholder="Search SKU, item, supplier or source"/></label><select value={status} onChange={(e)=>{setStatus(e.target.value);setPage(0)}} className="h-10 rounded-md border border-[var(--line)] bg-[var(--surface)] px-3 text-sm"><option value="all">All active</option><option value="open">Open</option><option value="ordered">PO ordered</option><option value="partial_received">Part received</option><option value="received">Received</option><option value="allocated">Allocated</option></select><select value={sort} onChange={(e)=>setSort(e.target.value)} className="h-10 rounded-md border border-[var(--line)] bg-[var(--surface)] px-3 text-sm"><option value="priority">Priority</option><option value="oldest">Oldest first</option><option value="sku_asc">SKU A–Z</option><option value="shortage_desc">Quantity high–low</option><option value="eta_asc">ETA soonest</option></select></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[960px] text-left text-sm"><thead className="bg-[var(--bg-soft)] text-[10px] uppercase tracking-wider text-[var(--ink-4)]"><tr><th className="p-4">SKU / item</th><th>Customer / order</th><th>Needed</th><th>PO / supplier</th><th>ETA</th><th className="pr-4">Action</th></tr></thead><tbody className="divide-y divide-[var(--line)]">{rows.map((row:any)=><tr key={row.id} className="hover:bg-[var(--bg-soft)]"><td className="p-4"><b>{row.sku} · {row.name}</b><p className="text-xs text-[var(--ink-4)]">{row.brand} · {row.finish||'Standard'}</p></td><td>{row.customer?.name||'Replenishment'}<p className="text-xs text-[var(--ink-4)]">{row.salesOrder?.orderNumber||row.sourceLineKey}</p></td><td>{row.quantity} {row.unit}<p className="text-xs text-[var(--ink-4)]">Received {row.receivedQuantity||0}</p></td><td><span className="rounded bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-800">{String(row.status).replaceAll('_',' ')}</span><p className="mt-1 text-xs">{row.vendorName||'Supplier pending'}</p></td><td>{row.expectedDate?new Date(row.expectedDate).toLocaleDateString('en-IN'):'Not set'}</td><td className="pr-4"><div className="flex gap-2"><Button asChild size="sm"><Link href="/dashboard/procurement?view=demand">Procure</Link></Button><Button asChild size="sm" variant="outline"><Link href="/dashboard/dispatch"><Truck className="mr-2 h-4 w-4"/>Dispatch</Link></Button></div></td></tr>)}{!loading&&!rows.length?<tr><td colSpan={6}><div className="grid min-h-64 place-items-center text-center"><div><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600"/><p className="mt-3 font-semibold">No pending inward rows match these filters.</p></div></div></td></tr>:null}</tbody></table></div><div className="flex items-center justify-between border-t border-[var(--line)] p-4"><span className="text-xs text-[var(--ink-4)]">Page {page+1} · {rows.length} shown</span><div className="flex gap-2"><Button size="icon" variant="outline" disabled={!page} onClick={()=>setPage(p=>p-1)}><ChevronLeft className="h-4 w-4"/></Button><Button size="icon" variant="outline" disabled={!result.hasNext} onClick={()=>setPage(p=>p+1)}><ChevronRight className="h-4 w-4"/></Button></div></div>
  </section>
 </div>
}
