'use client';

import { FormEvent, useState } from 'react';
import { gql, useMutation, useQuery } from '@apollo/client';
import { Save, Settings } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
const DATA=gql`query { appSettings { data } }`; const SAVE_SETTINGS=gql`mutation($input: UpdateSettingsInput!) { updateAppSettings(input:$input){ data } }`;
export default function SettingsPage(){const {data,refetch}=useQuery(DATA); const [form,setForm]=useState<any>({}); const [save,{loading}]=useMutation(SAVE_SETTINGS,{onCompleted:()=>{refetch();setForm({});}}); const settings=data?.appSettings?.data||{}; const merged={...settings,...form}; const submit=async(e:FormEvent)=>{e.preventDefault(); await save({variables:{input:{companyName:merged.companyName||'Marble Park',canonicalAppUrl:merged.canonicalAppUrl||'http://localhost:3001',quotePrefix:merged.quotePrefix||'QT',challanPrefix:merged.challanPrefix||'CH',approvalDiscountThreshold:Number(merged.approvalDiscountThreshold||15),supportPhone:merged.supportPhone||'',supportEmail:merged.supportEmail||''}}});}; return <div className="space-y-7 pb-10"><section className="rounded-r6 bg-[#18181b] p-7 text-white"><p className="text-xs font-medium uppercase tracking-[0.14em] text-[#71717a]">System settings</p><h1 className="mt-3 font-display text-3xl font-bold tracking-[-0.02em] text-[#18181b]">Company, quote and approval settings.</h1></section><form onSubmit={submit} className="mp-card rounded-r5 p-6"><Settings className="h-7 w-7 text-[#2563eb]"/><div className="mt-5 grid gap-4 md:grid-cols-2">{['companyName','canonicalAppUrl','quotePrefix','challanPrefix','supportPhone','supportEmail','approvalDiscountThreshold'].map(k=><label key={k} className="space-y-2"><span className="text-xs font-medium uppercase tracking-widest text-[#52525b]">{k}</span><Input type={k==='approvalDiscountThreshold'?'number':'text'} value={merged[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><Button className="mt-5" disabled={loading}><Save className="mr-2 h-4 w-4"/>Save settings</Button></form></div>}
