'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { gql, useMutation, useQuery } from '@apollo/client';
import { Ban, CalendarCheck, Check, ClipboardCheck, Scale, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { QueryErrorBanner } from '@/components/query-state';

const DATA = gql`query InventoryControlDesk {
  stockAdjustmentRequests(take: 100)
  inventoryPeriodCloses(take: 50)
  stockCountSessions(status: "posted", take: 50)
  inventoryLots(status: "active", take: 200)
}`;
const REQUEST = gql`mutation RequestAdjustment($input: StockAdjustmentRequestInput!) { requestStockAdjustment(input: $input) }`;
const DECIDE = gql`mutation DecideAdjustment($id: ID!, $action: String!, $input: StockAdjustmentDecisionInput) { decideStockAdjustment(id: $id, action: $action, input: $input) }`;
const CLOSE = gql`mutation ClosePeriod($input: InventoryPeriodCloseInput!) { closeInventoryPeriod(input: $input) }`;

export default function InventoryControlPage() {
  const now = new Date();
  const [lotId, setLotId] = useState('');
  const [adjustment, setAdjustment] = useState({ type: 'increase', quantity: '1', reason: '' });
  const [period, setPeriod] = useState({ periodType: 'monthly', periodKey: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`, countSessionId: '', effectiveAt: now.toISOString().slice(0, 10), notes: '' });
  const { data, error, refetch } = useQuery(DATA, { fetchPolicy: 'cache-and-network' });
  const [request, requestState] = useMutation(REQUEST, { onCompleted: () => { setAdjustment({ type: 'increase', quantity: '1', reason: '' }); refetch(); } });
  const [decide, decideState] = useMutation(DECIDE, { onCompleted: () => refetch() });
  const [close, closeState] = useMutation(CLOSE, { onCompleted: () => refetch() });
  const requests = useMemo<any[]>(() => data?.stockAdjustmentRequests || [], [data?.stockAdjustmentRequests]);
  const closes = data?.inventoryPeriodCloses || [];
  const counts = data?.stockCountSessions || [];
  const lots = data?.inventoryLots || [];
  const selectedLot = lots.find((lot: any) => lot.id === lotId);
  const pending = useMemo(() => requests.filter((row: any) => row.status === 'pending').length, [requests]);

  async function submitAdjustment() {
    const balance = selectedLot?.balances?.find((row: any) => Number(row.onHand) > 0) || selectedLot?.balances?.[0];
    if (!selectedLot || !balance) return;
    await request({ variables: { input: { productId: selectedLot.productId, lotId: selectedLot.id, locationId: balance.locationId, quantity: Number(adjustment.quantity), type: adjustment.type, reason: adjustment.reason } } });
  }

  return <div className="space-y-5 pb-10">
    {[error, requestState.error, decideState.error, closeState.error].filter(Boolean).map((item: any, index) => <QueryErrorBanner key={index} error={item}/>) }
    <header className="flex flex-col justify-between gap-4 border-b border-[var(--line)] pb-5 pt-2 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase text-[var(--ink-4)]">Governance</p><h1 className="mt-1 font-display text-3xl font-bold text-[var(--ink)]">Adjustments and period close</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--ink-3)]">Every correction names the exact lot and location, requires approval, and posts to the same universal ledger. Closing a month or year locks further stock postings for that period.</p></div><div className="flex gap-6"><div><p className="text-2xl font-semibold tabular-nums text-amber-700">{pending}</p><p className="text-xs text-[var(--ink-4)]">Awaiting approval</p></div><div><p className="text-2xl font-semibold tabular-nums text-[var(--ink)]">{closes.filter((row: any) => row.status === 'closed').length}</p><p className="text-xs text-[var(--ink-4)]">Periods closed</p></div></div></header>
    <section className="grid gap-5 xl:grid-cols-2">
      <div className="mp-panel p-4"><div className="flex items-center gap-2"><Scale className="h-5 w-5 text-[var(--brand-700)]"/><h2 className="font-semibold text-[var(--ink)]">Request lot adjustment</h2></div><div className="mt-4 space-y-3"><label className="block text-xs font-semibold text-[var(--ink-4)]">Exact stock lot<select value={lotId} onChange={(event) => setLotId(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-[var(--line)] bg-[var(--bg-soft)] px-3 text-sm"><option value="">Select lot</option>{lots.map((lot: any) => <option key={lot.id} value={lot.id}>{lot.product?.internalCode || lot.product?.sku} · {lot.lotNumber} · {lot.balances?.reduce((sum: number, row: any) => sum + Number(row.onHand || 0), 0)} on hand</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="block text-xs font-semibold text-[var(--ink-4)]">Type<select value={adjustment.type} onChange={(event) => setAdjustment({ ...adjustment, type: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-[var(--line)] bg-[var(--bg-soft)] px-3 text-sm"><option value="increase">Increase on hand</option><option value="decrease">Decrease available</option><option value="damage">Mark damaged</option><option value="damage_release">Release damaged</option><option value="hold">Place on hold</option><option value="hold_release">Release hold</option><option value="scrap_damage">Scrap damaged</option></select></label><label className="block text-xs font-semibold text-[var(--ink-4)]">Quantity<Input className="mt-1" type="number" min={1} value={adjustment.quantity} onChange={(event) => setAdjustment({ ...adjustment, quantity: event.target.value })}/></label></div><label className="block text-xs font-semibold text-[var(--ink-4)]">Reason<Input className="mt-1" value={adjustment.reason} onChange={(event) => setAdjustment({ ...adjustment, reason: event.target.value })} placeholder="Physical damage found during rack check"/></label><Button className="w-full" disabled={requestState.loading || !lotId || adjustment.reason.trim().length < 5} onClick={submitAdjustment}><ClipboardCheck className="mr-2 h-4 w-4"/>Submit for approval</Button></div></div>
      <div className="mp-panel p-4"><div className="flex items-center gap-2"><CalendarCheck className="h-5 w-5 text-[var(--brand-700)]"/><h2 className="font-semibold text-[var(--ink)]">Close inventory period</h2></div><div className="mt-4 space-y-3"><div className="grid grid-cols-2 gap-3"><label className="block text-xs font-semibold text-[var(--ink-4)]">Period type<select value={period.periodType} onChange={(event) => setPeriod({ ...period, periodType: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-[var(--line)] bg-[var(--bg-soft)] px-3"><option value="monthly">Monthly</option><option value="year_end">Year end</option></select></label><label className="block text-xs font-semibold text-[var(--ink-4)]">Period key<Input className="mt-1" value={period.periodKey} onChange={(event) => setPeriod({ ...period, periodKey: event.target.value })} placeholder={period.periodType === 'monthly' ? '2026-07' : '2026-27'}/></label></div><label className="block text-xs font-semibold text-[var(--ink-4)]">Posted physical count<select value={period.countSessionId} onChange={(event) => setPeriod({ ...period, countSessionId: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-[var(--line)] bg-[var(--bg-soft)] px-3"><option value="">Select matching posted count</option>{counts.filter((count: any) => count.countType === period.periodType).map((count: any) => <option key={count.id} value={count.id}>{count.countNumber} · {count.periodKey} · variance {count.totalVariance}</option>)}</select></label><label className="block text-xs font-semibold text-[var(--ink-4)]">Effective date<Input className="mt-1" type="date" value={period.effectiveAt} onChange={(event) => setPeriod({ ...period, effectiveAt: event.target.value })}/></label><label className="block text-xs font-semibold text-[var(--ink-4)]">Close notes<Input className="mt-1" value={period.notes} onChange={(event) => setPeriod({ ...period, notes: event.target.value })} placeholder="Physical count reviewed and variances approved"/></label><Button className="w-full" disabled={closeState.loading || !period.periodKey || !period.countSessionId} onClick={() => close({ variables: { input: { ...period, effectiveAt: new Date(`${period.effectiveAt}T23:59:59`).toISOString() } } })}><Ban className="mr-2 h-4 w-4"/>Close and lock period</Button><p className="text-xs leading-5 text-[var(--ink-4)]">Close only after procurement receipts, transfers and the matching monthly/year-end count are posted.</p></div></div>
    </section>
    <section className="mp-panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--line)] p-4"><div><h2 className="font-semibold text-[var(--ink)]">Adjustment approvals</h2><p className="mt-1 text-xs text-[var(--ink-4)]">Owner or stock-count approver decides every request.</p></div><Button asChild variant="outline" size="sm"><Link href="/dashboard/inventory/reconciliation">Open reconciliation</Link></Button></div><div className="divide-y divide-[var(--line)]">{requests.map((row: any) => <div key={row.id} className="grid gap-3 p-4 md:grid-cols-[1.4fr_1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-[var(--ink)]">{row.product?.internalCode || row.product?.sku} · {row.lot?.lotNumber}</p><span className="rounded bg-[var(--bg-soft)] px-2 py-1 text-xs font-semibold">{row.status}</span></div><p className="mt-1 text-xs text-[var(--ink-4)]">{row.location?.code} · {row.reason}</p></div><p className="text-sm"><b>{row.type.replace('_', ' ')}</b> · {row.quantity} units</p>{row.status === 'pending' ? <div className="flex gap-2"><Button size="sm" disabled={decideState.loading} onClick={() => decide({ variables: { id: row.id, action: 'approve' } })}><Check className="mr-2 h-4 w-4"/>Approve</Button><Button size="sm" variant="outline" disabled={decideState.loading} onClick={() => { const reason = window.prompt('Rejection reason'); if (reason) decide({ variables: { id: row.id, action: 'reject', input: { reason } } }); }}><X className="mr-2 h-4 w-4"/>Reject</Button></div> : <span className="text-xs text-[var(--ink-4)]">Decided {row.decidedAt ? new Date(row.decidedAt).toLocaleString('en-IN') : ''}</span>}</div>)}</div></section>
    <section className="mp-panel overflow-hidden"><div className="border-b border-[var(--line)] p-4"><h2 className="font-semibold text-[var(--ink)]">Period close register</h2></div><div className="divide-y divide-[var(--line)]">{closes.map((row: any) => <div key={row.id} className="grid gap-2 p-4 md:grid-cols-[1fr_auto_auto]"><div><p className="font-semibold text-[var(--ink)]">{row.closeNumber} · {row.periodKey}</p><p className="text-xs text-[var(--ink-4)]">{row.periodType.replace('_', ' ')} · {row.status}</p></div><span className="text-sm">{Number(row.totalQuantity || 0).toLocaleString('en-IN')} units</span><span className="text-sm">₹{Number(row.totalValue || 0).toLocaleString('en-IN')}</span></div>)}</div></section>
  </div>;
}
