'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { gql, useMutation, useQuery } from '@apollo/client';
import { AlertCircle as CircleAlert, ArrowLeft, BadgeCheck, BookOpen, Database, ExternalLink, Loader2, RotateCcw, Save, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { cn } from '@/lib/utils';

const SETUP = gql`query ReportingSetup { me { id name role effectivePermissions } reportingReadiness reportingTargets }`;
const SAVE_TARGET = gql`mutation SaveReportingTarget($input:JSON!){ saveReportingTarget(input:$input) }`;
const VOID_TARGET = gql`mutation VoidReportingTarget($id:ID!,$reason:String!){ voidReportingTarget(id:$id,reason:$reason) }`;

const metricLabels:Record<string,string> = { net_invoiced_sales:'Net invoiced sales', order_bookings:'Order bookings', collections:'Collections' };
const money = (value:unknown) => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(value||0));
const monthLabel = (value:string|Date) => new Intl.DateTimeFormat('en-IN',{month:'short',year:'numeric',timeZone:'Asia/Kolkata'}).format(new Date(value));

export default function ReportingSetupPage(){
  const currentMonth=useMemo(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit'}).format(new Date()),[]);
  const [form,setForm]=useState({metricKey:'net_invoiced_sales',month:currentMonth,amount:'',notes:''});
  const [voidId,setVoidId]=useState(''); const [voidReason,setVoidReason]=useState(''); const [notice,setNotice]=useState('');
  const {data,loading,error,refetch}=useQuery(SETUP,{fetchPolicy:'network-only'});
  const [saveTarget,{loading:saving,error:saveError}]=useMutation(SAVE_TARGET); const [voidTarget,{loading:voiding,error:voidError}]=useMutation(VOID_TARGET);
  const readiness:any[]=data?.reportingReadiness||[]; const targets:any[]=data?.reportingTargets||[];
  const activeTargets=targets.filter(item=>item.status==='active'); const history=targets.filter(item=>item.status!=='active');
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setNotice('');await saveTarget({variables:{input:{...form,amount:Number(form.amount)}}});setForm(current=>({...current,amount:'',notes:''}));setNotice('Target saved as a new governed version.');await refetch();};
  const confirmVoid=async()=>{if(!voidId)return;setNotice('');await voidTarget({variables:{id:voidId,reason:voidReason}});setVoidId('');setVoidReason('');setNotice('Target voided; its history remains in the register.');await refetch();};
  if(loading)return <div className="mp-panel grid min-h-[360px] place-items-center"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-[var(--brand-700)]"/><p className="mt-3 text-sm font-bold text-[var(--ink-4)]">Checking report sources…</p></div></div>;
  if(error)return <div className="rounded-xl border border-red-200 bg-red-50 p-5 text-sm font-bold text-red-800"><ShieldCheck className="mr-2 inline h-5 w-5"/>Reporting setup is restricted to owners and administrators.<p className="mt-2 font-semibold">{error.message}</p></div>;
  return <div className="mx-auto max-w-[1440px] space-y-5 pb-12">
    <header className="overflow-hidden rounded-xl bg-[#282321] p-5 text-[#fbf7f1] shadow-[0_8px_24px_rgba(35,30,28,.08)] sm:p-7">
      <Link href="/dashboard/reports" className="inline-flex min-h-10 items-center text-xs font-black text-[#dcb1ab]"><ArrowLeft className="mr-2 h-4 w-4"/>Back to report suites</Link>
      <div className="mt-3 grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div><p className="text-[9px] font-black uppercase tracking-[.16em] text-[#dcb1ab]">Governed source readiness</p><h1 className="mt-2 text-2xl font-black tracking-tight text-white sm:text-3xl">Make missing report data actionable</h1><p className="mt-3 max-w-3xl text-sm font-medium leading-6 text-[#c9c0b8]">Close only the source gaps Marble Park can safely own. Existing operational masters stay authoritative; accounting facts require a real subledger or integration.</p></div><div className="rounded-xl bg-white/[.065] p-4 shadow-[inset_0_0_0_1px_rgba(255,255,255,.08)]"><BookOpen className="h-5 w-5 text-[#dcb1ab]"/><p className="mt-3 text-sm font-black text-white">Need the workflow?</p><p className="mt-1 text-xs font-medium leading-5 text-[#c9c0b8]">The readiness guide explains ownership, prerequisites, capture points and why some values cannot be typed here.</p><Link href="/dashboard/help#reporting-readiness" className="mt-3 inline-flex min-h-10 items-center text-xs font-black text-[#e6b8b2]">Open readiness guide<ExternalLink className="ml-2 h-3.5 w-3.5"/></Link></div></div>
    </header>

    {notice?<div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800"><BadgeCheck className="mr-2 inline h-5 w-5"/>{notice}</div>:null}
    {(saveError||voidError)?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-800"><CircleAlert className="mr-2 inline h-5 w-5"/>{saveError?.message||voidError?.message}</div>:null}

    <section aria-labelledby="readiness-heading"><div className="flex items-end justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.14em] text-[var(--brand-700)]">Source map</p><h2 id="readiness-heading" className="mt-1 text-xl font-black text-[var(--ink)]">What can be fixed here—and what cannot</h2></div></div><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{readiness.map(area=><article id={area.id==='targets'?'targets':area.id==='supplier_ap'?'supplier-ap':area.id==='accounting'?'accounting':area.id==='quoted_margin'?'cost-provenance':undefined} key={area.id} className="mp-panel scroll-mt-24 p-4"><div className="flex items-start gap-3"><span className={cn('grid h-10 w-10 shrink-0 place-items-center rounded-xl',area.status==='ready'?'bg-emerald-50 text-emerald-700':area.status==='external_required'?'bg-violet-50 text-violet-700':'bg-amber-50 text-amber-700')}>{area.status==='ready'?<BadgeCheck className="h-5 w-5"/>:area.status==='external_required'?<Database className="h-5 w-5"/>:<CircleAlert className="h-5 w-5"/>}</span><div className="min-w-0"><p className="text-sm font-black text-[var(--ink)]">{area.title}</p><p className="mt-1 text-[10px] font-black uppercase tracking-wider text-[var(--ink-4)]">{area.classification.replaceAll('_',' ')}</p></div></div><p className="mt-4 text-xs font-bold leading-5 text-[var(--ink-3)]">{area.sourceStatus}</p><p className="mt-2 text-xs font-medium leading-5 text-[var(--ink-4)]">{area.message}</p><div className="mt-4 border-t border-[var(--line)] pt-3"><p className="text-[9px] font-black uppercase tracking-wider text-[var(--ink-4)]">Owner</p><p className="mt-1 text-xs font-bold text-[var(--ink-2)]">{area.owner}</p>{area.actionHref!==`/dashboard/reports/setup#${area.id}`&&area.id!=='targets'?<Link href={area.actionHref} className="mt-3 inline-flex min-h-10 items-center text-xs font-black text-[var(--brand-700)]">{area.actionLabel}<ExternalLink className="ml-2 h-3.5 w-3.5"/></Link>:null}</div></article>)}</div></section>

    <section className="grid scroll-mt-24 gap-4 xl:grid-cols-[420px_minmax(0,1fr)]" id="target-entry"><form onSubmit={submit} className="mp-panel p-5"><p className="text-[9px] font-black uppercase tracking-[.14em] text-[var(--brand-700)]">Authorized entry</p><h2 className="mt-1 text-xl font-black text-[var(--ink)]">Set a monthly company target</h2><p className="mt-2 text-xs font-medium leading-5 text-[var(--ink-4)]">Saving the same metric and month creates a revision. It never overwrites or deletes the prior version.</p><div className="mt-5 space-y-4"><label className="grid gap-1 text-xs font-black text-[var(--ink-3)]">Metric<Select value={form.metricKey} onChange={event=>setForm({...form,metricKey:event.target.value})}><option value="net_invoiced_sales">Net invoiced sales</option><option value="order_bookings">Order bookings</option><option value="collections">Collections</option></Select></label><label className="grid gap-1 text-xs font-black text-[var(--ink-3)]">Month<Input type="month" required value={form.month} onChange={event=>setForm({...form,month:event.target.value})}/></label><label className="grid gap-1 text-xs font-black text-[var(--ink-3)]">Target amount (₹)<Input type="number" min="0.01" step="0.01" required inputMode="decimal" value={form.amount} onChange={event=>setForm({...form,amount:event.target.value})} placeholder="Enter approved amount"/></label><label className="grid gap-1 text-xs font-black text-[var(--ink-3)]">Source note / approval reference<Input value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})} maxLength={500} placeholder="Optional board plan, owner approval or context"/></label><Button className="w-full" disabled={saving}><Save className="mr-2 h-4 w-4"/>{saving?'Saving version…':'Save governed target'}</Button></div></form>
      <div className="mp-panel overflow-hidden"><div className="border-b border-[var(--line)] p-5"><h2 className="text-lg font-black text-[var(--ink)]">Active target register</h2><p className="mt-1 text-xs font-medium text-[var(--ink-4)]">The Target vs Actual report uses only active rows. Revisions and voids remain below.</p></div><div className="overflow-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-[var(--bg-soft)] text-[9px] font-black uppercase tracking-wider text-[var(--ink-4)]"><tr><th className="px-4 py-3">Month</th><th className="px-4 py-3">Metric</th><th className="px-4 py-3 text-right">Target</th><th className="px-4 py-3">Version</th><th className="px-4 py-3">Note</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{activeTargets.map(target=><tr key={target.id} className="border-t border-[var(--line)]"><td className="px-4 py-3 font-black">{monthLabel(target.periodStart)}</td><td className="px-4 py-3 font-bold">{metricLabels[target.metricKey]||target.metricKey}</td><td className="px-4 py-3 text-right font-black tabular-nums">{money(target.amount)}</td><td className="px-4 py-3">v{target.version}</td><td className="max-w-[260px] truncate px-4 py-3 text-[var(--ink-4)]">{target.notes||'—'}</td><td className="px-4 py-3"><Button variant="secondary" onClick={()=>{setVoidId(target.id);setVoidReason('')}}><RotateCcw className="mr-1 h-3.5 w-3.5"/>Void</Button></td></tr>)}{!activeTargets.length?<tr><td colSpan={6} className="p-10 text-center font-semibold text-[var(--ink-4)]">No active targets. Add the first approved monthly target using the guided form.</td></tr>:null}</tbody></table></div>{voidId?<div className="border-t border-amber-200 bg-amber-50 p-4"><label className="grid gap-1 text-xs font-black text-amber-900">Why is this target being voided?<Input autoFocus value={voidReason} minLength={5} maxLength={500} onChange={event=>setVoidReason(event.target.value)} placeholder="Required audit reason" className="bg-white"/></label><div className="mt-3 flex flex-wrap gap-2"><Button disabled={voiding||voidReason.trim().length<5} onClick={confirmVoid}>{voiding?'Voiding…':'Confirm void'}</Button><Button variant="secondary" onClick={()=>{setVoidId('');setVoidReason('')}}>Keep target</Button></div></div>:null}</div>
    </section>

    <details className="mp-panel overflow-hidden"><summary className="cursor-pointer list-none p-5 text-sm font-black text-[var(--ink)]">Revision and void history <span className="ml-2 text-xs text-[var(--ink-4)]">({history.length})</span></summary><div className="border-t border-[var(--line)] p-4"><div className="grid gap-2 md:grid-cols-2">{history.map(target=><div key={target.id} className="rounded-xl bg-[var(--bg-soft)] p-3 text-xs"><div className="flex items-center justify-between gap-3"><p className="font-black">{monthLabel(target.periodStart)} · {metricLabels[target.metricKey]||target.metricKey}</p><span className="rounded-full bg-[var(--surface)] px-2 py-1 text-[9px] font-black uppercase">{target.status} · v{target.version}</span></div><p className="mt-2 font-bold">{money(target.amount)}</p>{target.voidReason?<p className="mt-2 text-[var(--ink-4)]">Reason: {target.voidReason}</p>:null}</div>)}{!history.length?<p className="text-xs font-semibold text-[var(--ink-4)]">No target revisions or voids yet.</p>:null}</div></div></details>
  </div>;
}
